server:
  port: 8084
spring:
#  datasource:
#    url: jdbc:mysql://${DB_HOST:localhost}:3306/productdb
#    #url: jdbc:mysql://localhost:3306/productdb
#    username: root
#    password: mysql_nikhil
#    driverClassName: com.mysql.cj.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
  application:
    name: COMMON-SERVICE
  config:
    import: configserver:http://localhost:9296
