services:
 db:
    image: mysql
    ports:
      - "3306:3306"
    environment: 
        MYSQL_ROOT_PASSWORD: mysql_nikhil
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springboot-mysql-net
 phpMyAdmin:
    image: phpmyadmin
    environment:
        PMA_ARBITRARY: 1
    ports:
        - "8081:80"
    networks:
      - springboot-mysql-net
volumes:
  mysql_data:
networks:
  springboot-mysql-net:
    driver: bridge